# Basic config
baseURL = "https://ingo-richter.io/"
languageCode = "en"                # zh-Hans
title = "Today is Tomorrow's Past"
copyright = "© 2025 Ingo Richter"
timezone = "America/Los_Angeles"
timeout = 60

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# just in case I forgot to provide <!--more--> in the post then hugo will automatically
# truncate the content to the summaryLength
summaryLength = 50

[module]
[module.hugoVersion]
extended = true
min = "0.62.0"
[[module.imports]]
path = 'github.com/maolonglong/hugo-simple'

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
# disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
blog = "/:slugorcontentbasename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Today is Tomorrow's Past"
description = "I write about web technologies, iOS, macOS, SwiftUI, javascript, typescript, reactjs, nodejs, process automation, jenkins, docker, kubernetes, 3dprinting, penplotter and lasercutting"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = false
style = "custom.css"

[params.author]
name = "Ingo Richter"
email = "ingo@ingo-richter.io"
fediverse = "@ingorichter@mastodon.social"
location = "Greater Bay Area"
bio = "simple is harder than complex"
paragraph = "I help people create remarkable things. Focus on the customer and quality. Opinions are my own. <i class='fa fa-camera-retro' aria-hidden='true'></i> Photography is my other passion.<i class='fa fa-hand-peace-o'></i>"

[menus]
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20
[[menus.main]]
name = "Resume"
URL = "/resume/resume.pdf"
weight = 30
[[menus.main]]
name = "Posts"
pageRef = "/post"
weight = 40
[[menus.main]]
name = "CV19WFH"
pageRef = "/cv19wfh"
weight = 50
[[menus.main]]
name = "Wallpaper"
pageRef = "/wallpaper"
weight = 60
[[menus.main]]
name = "Categories"
pageRef = "/categories"
weight = 70

[services.rss]
limit = 42

[pagination]
pagerSize = 16

[outputs]
page = ["html", "rss"]
home = ["html", "json", "rss"]
section = ["html", "rss"]
taxonomy = ["html", "rss"]
term = ["html", "rss"]

# enable disqus for now
[services]
[services.disqus]
shortname = 'ingorichterio'

[params.umamiAnalytics]
id = "98a5f2cb-a53b-4d84-9133-bac4957e9e9f"
src = "https://umami.familie-richter.de/script.js"
