.SHELLFLAGS := -eu -o pipefail -c

# PHONY means that there will be no files generated by this task
.PHONY: preview
preview:
	hugo server -D --printI18nWarnings -v --templateMetrics --templateMetricsHints --disableFastRender

# .PHONY: newpost
# make newpost title="This is the title"
newpost:
	hugo new post/$$(date +"%Y")/$$(echo '${title}' | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g')/index.md

# make cv19 title="This is the title"
STARTDATE="2020-16-03"
.PHONY: cv19
cv19:
# add 1 day to include the current day
	$(eval DAYS=$(shell echo "($(shell date +%s) - $(shell date -jf "%Y-%d-%m" "2020-16-03" +%s)) / 86400 + 1" | bc))
	hugo new cv19wfh/$$(date +"%Y")/$$(date +"%m")/day$(DAYS)/index.md

.PHONY: updateLazysize
updateLazysize:
# download the javascript library
	curl -v -L https://raw.githubusercontent.com/aFarkas/lazysizes/gh-pages/lazysizes.js -o assets/js/external/lazysizes.js

.PHONY: updateSubmodules
updateSubmodules:
	git submodule update --remote
