.SHELLFLAGS := -eu -o pipefail -c

# PHONY means that there will be no files generated by this task
.PHONY: preview
preview:
	hugo server -D --i18n-warnings -v --templateMetrics --templateMetricsHints --disableFastRender

# .PHONY: newpost
# make newpost title="This is the title"
newpost:
	hugo new post/$$(date +"%Y")/$$(echo '${title}' | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g')/index.md

# make cv19 title="This is the title"
STARTDATE="2020-16-03"
.PHONY: cv19
cv19:
	$(eval DAYS=$(shell echo "($(shell date +%s) - $(shell date -jf "%Y-%d-%m" "2020-16-03" +%s)) / 86400" | bc))
	hugo new cv19wfh/$$(date +"%Y")/day$(DAYS)/index.md