+++
date = "2016-06-16T20:15:51-07:00"
draft = false
title = "TIL - where to put ant-contrib"
tags  = [ "TIL", "Tips", "Programming", "Java", "Ant" ]
topics = [ "TIL", "Tips", "Programming" ]
categories = [ "Tips", "Programming" ]
+++

I was testing an https://ant.apache.org/[ant] based build script change today. And I thought https://ant.apache.org/[ant] was already retired. 

Running the script led to a lot of warnings about a missing library. I asked the person, if there are any dependencies for http://ant-contrib.sourceforge.net/[ant-contrib]. His response was "yes, you need to install http://ant-contrib.sourceforge.net/[ant-contrib]".

First of all, I didn't have https://ant.apache.org/[ant] installed. But that was easy with

[source, bash]
----
irichter@irichter-MacBookPro:~ brew install ant
----

Unfortunately, http://ant-contrib.sourceforge.net/[ant-contrib] wasn't available via homebrew, so I had to download it and place it... where?
Ah, in the `lib` folder of your https://ant.apache.org/[ant] installation. Okay, that might one solution. I remembered, that years ago I was using it in a different way. There was another location where ant was looking for additional jars.

## This worked for me 

. create or locate the `~/.ant/lib` directory
. copy all additional jars in this directory

From now on, https://ant.apache.org/[ant] will be able to find http://ant-contrib.sourceforge.net/[ant-contrib] and I don't have to mess around with the https://ant.apache.org/[ant] installation directory.
Clean, nice and simple solution.

NOTE: I don't know, if this will work on Windows in the same way.

Thanks for reading!