name: Sanity Check

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches: # Specify branches or use a wildcard for all branches
      - '*' # Matches all branches
      # Alternatively, you can list specific branches:
      # - master
      # - develop
      # - feature/*
  pull_request: # Optionally, run on pull requests too
    branches:
      - '*' # Matches all branches

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable' # Use the latest version of Go

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Go Modules Dependencies
        run: hugo mod get -u ./...

      - name: Build
        run: hugo --printI18nWarnings --minify